### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by timothee-haudebourg** [jFransham/smallstring#7]
Hi,

This crate is quite useful but has not been updated in a while. I can offer to take ownership of the crate to continue the development and maintenance if you want.

**Comment by Kerollmops** [comment]
I think this crate is kind of deprecated, I personnaly use [smallstr](lib.rs/smallstr) now.

**Comment by timothee-haudebourg** [comment]
Yes I see that. I should close the issue.
